### ISSUE TITLE
svelte-3-example doesn't work

### ISSUE THREAD

**Issue by trafnar** [DeMoorJasper/parcel-plugin-svelte#45] opened 2019-04-29 18:52 UTC
# 🐛 Bug Report

The included svelte-3-example directory doesn't work for me. I downloaded it, did `npm install`, then `npm run start` and I get these errors in the browser:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/6732/56919367-3d14c500-6a75-11e9-8187-d3a158994d84.png">

## 🎛 Configuration (.svelterc, package.json, cli command)

I'm not using any custom config.

## 💻 Code Sample

The code is directly from the `svelte-3-example` directory

## 🌍 Your Environment

    "parcel-plugin-svelte": "^3.0.0",
    "svelte": "^3.0.0"

**Comment by DeMoorJasper** [comment] 2019-04-29 19:16
Yes it doesn’t work I didn’t have time to debug it, it’s the same issue that had already been reported. Svelte 2 still works though with v2 release of this plugin.

I’ll try look into this asap but haven’t really used svelte a lot besides writing this plugin and experimenting a lil with it

If anyone wants to debug this feel free to do so

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by trafnar** [comment] 2019-04-29 19:55
Ah ok, I wasn't sure if it was expected to work currently.

Totally understand, thanks for your work on this project. I might try to fix it myself if I find time.

**Comment by michaelauderer** [comment] 2019-05-04 20:27
Duplicate of #44

**Closed** 2019-05-04 20:36 UTC
